<?php
require_once 'session_check.php';
// Hidden Database Export Utility
// WARNING: This file should be protected and accessed only by authorized administrators

// Start session and include database configuration
session_start();
require_once 'config.php';

// Security check - require login only
if (!isset($_SESSION['user_id'])) {
    http_response_code(403);
    die("Access Denied: Please login first.");
}

// Any logged-in user can export the database

// Set execution time limit for large databases
set_time_limit(300); // 5 minutes
ini_set('memory_limit', '512M');

// Export format: SQL dump
$export_format = isset($_GET['format']) ? $_GET['format'] : 'sql';

// Get database name from config
global $dbname, $conn;

// Function to export database as SQL
function exportDatabaseAsSQL($conn, $dbname) {
    $output = "-- MOTOGAM Database Export\n";
    $output .= "-- Database: {$dbname}\n";
    $output .= "-- Export Date: " . date('Y-m-d H:i:s') . "\n";
    $output .= "-- Generated by: hiddenexportalldatabase.php\n\n";
    $output .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $output .= "SET time_zone = \"+00:00\";\n";
    $output .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
    
    // Get all tables
    $tables_result = $conn->query("SHOW TABLES");
    if (!$tables_result) {
        return "Error: Unable to retrieve table list.";
    }
    
    $tables = array();
    while ($row = $tables_result->fetch_array()) {
        $tables[] = $row[0];
    }
    
    // Export each table
    foreach ($tables as $table) {
        $output .= "\n-- --------------------------------------------------------\n";
        $output .= "-- Table structure for table `{$table}`\n";
        $output .= "-- --------------------------------------------------------\n\n";
        
        // Drop table if exists
        $output .= "DROP TABLE IF EXISTS `{$table}`;\n";
        
        // Get table structure
        $create_table = $conn->query("SHOW CREATE TABLE `{$table}`");
        if ($create_table) {
            $row = $create_table->fetch_row();
            $output .= $row[1] . ";\n\n";
        }
        
        // Get table data
        $output .= "-- Dumping data for table `{$table}`\n\n";
        
        $data_result = $conn->query("SELECT * FROM `{$table}`");
        if ($data_result && $data_result->num_rows > 0) {
            $num_fields = $data_result->field_count;
            
            while ($row = $data_result->fetch_row()) {
                $output .= "INSERT INTO `{$table}` VALUES(";
                
                for ($j = 0; $j < $num_fields; $j++) {
                    if (isset($row[$j])) {
                        $row[$j] = $conn->real_escape_string($row[$j]);
                        $output .= '"' . $row[$j] . '"';
                    } else {
                        $output .= 'NULL';
                    }
                    
                    if ($j < ($num_fields - 1)) {
                        $output .= ',';
                    }
                }
                
                $output .= ");\n";
            }
        }
        
        $output .= "\n";
    }
    
    $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
    
    return $output;
}

// Function to export database as JSON
function exportDatabaseAsJSON($conn, $dbname) {
    $export_data = array(
        'database' => $dbname,
        'export_date' => date('Y-m-d H:i:s'),
        'tables' => array()
    );
    
    // Get all tables
    $tables_result = $conn->query("SHOW TABLES");
    if (!$tables_result) {
        return json_encode(['error' => 'Unable to retrieve table list']);
    }
    
    while ($row = $tables_result->fetch_array()) {
        $table = $row[0];
        
        // Get table structure
        $columns_result = $conn->query("SHOW COLUMNS FROM `{$table}`");
        $columns = array();
        while ($col = $columns_result->fetch_assoc()) {
            $columns[] = $col;
        }
        
        // Get table data
        $data_result = $conn->query("SELECT * FROM `{$table}`");
        $rows = array();
        if ($data_result) {
            while ($data_row = $data_result->fetch_assoc()) {
                $rows[] = $data_row;
            }
        }
        
        $export_data['tables'][$table] = array(
            'structure' => $columns,
            'data' => $rows,
            'row_count' => count($rows)
        );
    }
    
    return json_encode($export_data, JSON_PRETTY_PRINT);
}

// Process export based on format
try {
    if ($export_format === 'sql') {
        $filename = $dbname . '_backup_' . date('Y-m-d_H-i-s') . '.sql';
        $content = exportDatabaseAsSQL($conn, $dbname);
        
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($content));
        
        echo $content;
        
    } elseif ($export_format === 'json') {
        $filename = $dbname . '_backup_' . date('Y-m-d_H-i-s') . '.json';
        $content = exportDatabaseAsJSON($conn, $dbname);
        
        header('Content-Type: application/json');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($content));
        
        echo $content;
        
    } else {
        http_response_code(400);
        die("Invalid export format. Supported formats: sql, json");
    }
    
    // Log export activity
    $user_id = $_SESSION['user_id'];
    $log_sql = "INSERT INTO activity_logs (user_id, action, timestamp) VALUES (?, 'Database Export', NOW())";
    $stmt = $conn->prepare($log_sql);
    if ($stmt) {
        $stmt->bind_param("i", $user_id);
        $stmt->execute();
        $stmt->close();
    }
    
} catch (Exception $e) {
    http_response_code(500);
    die("Export Error: " . $e->getMessage());
}

$conn->close();
exit;
?>
